site_name: V-Control Pro User Guide
site_description: User Guide for V-Control Pro.
site_url: https://docs.neyrinck.com/v-control-pro/

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
plugins:
  - search
  - include-markdown
nav:
  - Home:
    - ./index.md
    - Additional Resources: './getting-help.md'
  - What's New:
    - Version 3.3: './whats-new/version-3-3.md'
    - Version 3.2: './whats-new/version-3-2.md'
    - Version 3.2.1: './whats-new/version-3-2-1.md'
  - Getting started:
    - Important Information: './important-info.md'
    - Quick Start Guide: './quick-start-guide.md'
    - Install And Run V-Control Pro : './install-and-run-v-control-pro.md'
    - System Requirements: './requirements.md'
  - Licensing: './v-control-pro-licensing.md'
  - Surface Setup:
    - Overview: './controllers-overview.md'
    - Setting Up Ethernet Controllers: './ethernet-controllers.md'
    - Setting Up MIDI Controllers: './midi-controllers.md'
    - Setting Up FireWire Controllers: './firewire-controllers.md'
    - Avid D-Command: './d-command.md'
    - Avid D-Control Basic: './d-control.md'
    - Digidesign Control 24: './control-24.md'
    - Avid/Digidesign C|24: './c24.md'
    - Digidesign ProControl: './pro-control.md'
    - Digidesign Command 8: './command8.md'
    - Digidesign 003: './digidesign-003.md'
    - FaderPort V2 / ioStation 24c: './faderport-v2.md'
    - FaderPort 8 / 16: './faderport-8-16.md'
    - V-Console: './v-console.md'
    - V-Control Pro iPad App: './v-control-pro-ipad.md'
    - Multiple HUI Controllers With Pro Tools: './hui-device.md'
  - DAW/Application Setup:
    - Pro Tools: './pro-tools.md'
    - Logic Pro: './logic-pro.md'
    - Cubase / Nuendo: './cubase-nuendo.md'
    - Mackie Control DAWs:
      - Getting Started: './mackie-control.md'
      - Ableton Live: './ableton-live.md'
      - Adobe Audition: './adobe-audition.md'
      - DaVinci Resolve: './davinci-resolve.md'
      - Digital Performer: './digital-performer.md'
      - FL Studio: './fl-studio.md'
      - FMOD Studio: './fmod-studio.md'
      - LUNA: './luna.md'
      - MIO Console: './mio-console.md'
      - MixBus: './mixbus.md'
      - Premiere Pro: './premiere-pro.md'
      - Reaper: './reaper.md'
      - Reason: './reason.md'
      - Sonar: './sonar.md'
      - Studio One / Fender Studio: './studio-one.md'
      - Tracktion: './tracktion.md'
      - Wwise: './wwise.md'
  - MIDI Mode: './midi-mode.md'
  - V-Window: './v-window.md'
  - Feature Charts:
    - Overview: './feature-charts.md'
    - D-Command:
      - D-Command - Pro Tools: './feature-chart/dcommand-protools.md'
      - D-Command - Logic Pro: './feature-chart/dcommand-logic.md'
      - D-Command - Studio One / Fender Studio: './feature-chart/dcommand-studio-one.md'
      - D-Command - Cubase / Nuendo: './feature-chart/dcommand-steinberg.md'
      - D-Command - MixBus: './feature-chart/dcommand-mixbus.md'
    - D-Control Basic:
      - D-Control Basic - Pro Tools: './feature-chart/dcontrol-protools.md'
    - C|24:
      - C|24 - Pro Tools: './feature-chart/c24-protools.md'
      - C|24 - Logic Pro: './feature-chart/c24-logic.md'
      - C|24 - Studio One / Fender Studio: './feature-chart/c24-studio-one.md'
      - C|24 - Cubase / Nuendo: './feature-chart/c24-steinberg.md'
      - C|24 - MixBus: './feature-chart/c24-mixbus.md'
      - C|24 - Digital Performer: './feature-chart/c24-performer.md'
      - C|24 - Ableton Live: './feature-chart/c24-ableton-live.md'
      - C|24 - LUNA: './feature-chart/c24-luna.md'
    - Control 24:
      - Control 24 - Pro Tools: './feature-chart/control24-protools.md'
      - Control 24 - Logic Pro: './feature-chart/control24-logic.md'
      - Control 24 - Studio One / Fender Studio: './feature-chart/control24-studio-one.md'
      - Control 24 - Cubase / Nuendo: './feature-chart/control24-steinberg.md'
      - Control 24 - MixBus: './feature-chart/control24-mixbus.md'
      - Control 24 - Digital Performer: './feature-chart/control24-performer.md'
      - Control 24 - Ableton Live: './feature-chart/control24-ableton-live.md'
      - Control 24 - LUNA: './feature-chart/control24-luna.md'
    - ProControl:
      - ProControl - Pro Tools: './feature-chart/procontrol-protools.md'
      - ProControl - Logic Pro: './feature-chart/procontrol-logic.md'
      - ProControl - Studio One / Fender Studio: './feature-chart/procontrol-studio-one.md'
      - ProControl - Cubase / Nuendo: './feature-chart/procontrol-steinberg.md'
      - ProControl - MixBus: './feature-chart/procontrol-mixbus.md'
      - ProControl - Digital Performer: './feature-chart/procontrol-performer.md'
      - ProControl - Ableton Live: './feature-chart/procontrol-ableton-live.md'
      - ProControl - LUNA: './feature-chart/procontrol-luna.md'
    - Command 8:
      - Command 8 - Pro Tools: './feature-chart/command8-protools.md'
      - Command 8 - Logic Pro: './feature-chart/command8-logic.md'
      - Command 8 - Studio One / Fender Studio: './feature-chart/command8-studio-one.md'
      - Command 8 - Cubase / Nuendo: './feature-chart/command8-steinberg.md'
      - Command 8 - Ableton Live: './feature-chart/command8-ableton-live.md'
      - Command 8 - LUNA: './feature-chart/command8-luna.md'
    - FaderPort 8 / 16:
      - FaderPort 8 / 16 - Pro Tools 2023 and later: './feature-chart/faderport-8-16-protools-2023.md'
    - FaderPort V2 / ioStation 24c:
      - FaderPort V2 / ioStation 24c - Pro Tools: './feature-chart/faderport-v2-protools.md'
    - Digi 003:
      - Digi 003 - Logic Pro: './feature-chart/003-logic.md'
      - Digi 003 - Studio One / Fender Studio: './feature-chart/003-studio-one.md'
      - Digi 003 - Cubase / Nuendo: './feature-chart/003-steinberg.md'
      - Digi 003 - Ableton Live: './feature-chart/003-ableton-live.md'
      - Digi 003 - LUNA: './feature-chart/003-luna.md'
  - Troubleshooting: './troubleshooting.md'
  - Release Notes: './release-notes.md'

markdown_extensions:
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/unsupported-browser.js