site_name: V-Control Pro User Guide
site_description: User Guide for V-Control Pro.

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
plugins:
  - include-markdown
nav:
  - Home:
    - ./index.md
    - Additional Resources: './getting-help.md'
  - Getting started:
    - Quick Start Guide: './quick-start-guide.md'
    - Install And Run V-Control Pro : './install-and-run-v-control-pro.md'
    - System Requirements: './requirements.md'
  - Licensing: './v-control-pro-licensing.md'
  - Surface Setup:
    - Overview: './controllers-overview.md'
    - Setting Up Ethernet Controllers: './ethernet-controllers.md'
    - Setting Up MIDI Controllers: './midi-controllers.md'
    - Setting Up FireWire Controllers: './firewire-controllers.md'
    - Avid D-Command: './d-command.md'
    - Digidesign Control 24: './control-24.md'
    - Avid/Digidesign C|24: './c24.md'
    - Digidesign ProControl: './pro-control.md'
    - Digidesign Command 8: './command8.md'
    - Digidesign 003: './digidesign-003.md'
    - FaderPort V2 / ioStation 24c: './faderport-v2.md'
    - FaderPort 8 / 16: './faderport-8-16.md'
    - V-Console: './v-console.md'
    - V-Control Pro iPad App: './v-control-pro-ipad.md'
  - DAW/Application Setup:
    - Pro Tools: './pro-tools.md'
    - Logic Pro X: './logic-pro.md'
    - Cubase / Nuendo: './cubase-nuendo.md'
    - Mackie Control DAWs:
      - Getting Started: './mackie-control.md'
      - Ableton Live: './ableton-live.md'
      - Adobe Audition: './adobe-audition.md'
      - DaVinci Resolve: './davinci-resolve.md'
      - Digital Performer: './digital-performer.md'
      - FL Studio: './fl-studio.md'
      - FMOD Studio: './fmod-studio.md'
      - LUNA: './luna.md'
      - MIO Console: './mio-console.md'
      - MixBus: './mixbus.md'
      - Premiere Pro: './premiere-pro.md'
      - Reaper: './reaper.md'
      - Reason: './reason.md'
      - Sonar: './sonar.md'
      - Studio One: './studio-one.md'
      - Tracktion: './tracktion.md'
      - Wwise: './wwise.md'
  - MIDI Mode: './midi-mode.md'
  - V-Window: './v-window.md'
  - Feature Charts: './feature-charts.md'
  - Troubleshooting: './troubleshooting.md'
  - Release Notes: './release-notes.md'
  
markdown_extensions:
  - attr_list
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/unsupported-browser.js